---
title: "Lab 1 Homework"
author: "Vaishnavi Maganti"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
---

## Instructions
Answer the following questions and/or complete the exercises in RMarkdown. Please embed all of your code and push the final work to your repository. Your report should be organized, clean, and run free from errors. Remember, you must remove the `#` for any included code chunks to run.  

**1. Please tell us why you are taking BIS 15L.**

I am taking BIS 15L because I've always been passionate about both coding and biology, and this course gives me the opportunity to tackle both together. I am also very interested in bioinformatics and biotechnology, and I know that coding is a large part of genetic analysis and various other techniques in research, so I am taking this course to also address that. 

**2. Do you have any coding experience? If yes, please tell us what languages you have coded in and your level of experience.**

I have minimal coding experience, as I have only taken 2 years of computer science in middle school with a brief introduction to JavaScript and Python. Since it has been a while, my level of experience is unreliable and I am close to a beginner.

**3. Navigate to the `datascibiol` repository on GitHub. Notice that near the bottom there is a description of the repository. You want something like this on your repository! It is built by making edits to the `README.md` file using RMarkdown. Edit your repository's `README.md` file so that you have an informative description, including your email address. Be creative! You don't need to just copy mine. There are lots of examples online.**  

**4. Please put a link to your GitHub repository below.**

https://github.com/vmagiant-coder/BIS15L_W26_vmaganti

**5. Make sure that your repository includes the practice file `dummy_push` from lab 1.2. If you have not done so already, please add your name to this file, knit it, and push it to your repository.**  

## Knit and Upload
Please knit your work as an .html file and upload to Canvas. Homework is due before the start of the next lab. No late work is accepted. Make sure to use the formatting conventions of RMarkdown to make your report neat and clean!  